name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: read

jobs:
  unit-test:
    name: unit-test
    strategy:
      matrix:
        python-version: [ 3.6, 3.8, 3.10 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements/dev.txt ]; then pip install -r requirements/dev.txt; fi
    - name: Install package/self
      run: |
        pip install -e .
    - name: Test with pytest
      run: |
        pytest test/**
